# Generated by Django 4.0.3 on 2022-03-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platformuser_is_disabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformuser',
            old_name='is_user_blocked',
            new_name='is_login_blocked',
        ),
    ]
