# Generated by Django 4.0.3 on 2022-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_user_blocked_platformuser_is_login_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
